Added border color for areas
mapsme/kothic pull request #30
Opened 2017-02-13 11:29 UTC by rokuz

2017-02-13 11:32 UTC, therearesomewhocallmetim commented
LGTM

2017-02-13 11:38 UTC, Komzpa commented
guys, border color for areas is called 'casing' in MapCSS and is already there :)

2017-02-13 14:59 UTC, rokuz commented
Thank you. Do you mean that I have to rename 'border-color' to 'casing'? No problem. But what do you mean by "already there"? No line in libkomwm.py writes in _area.border_ before.

2017-02-13 15:25 UTC, Komzpa commented
There's a common spec for all this - http://wiki.openstreetmap.org/wiki/MapCSS/0.2 - have a look there each time you'd like to reinvent something :)

By MapCSS design, what you call 'border' here is in fact the linear geometry of feature.

In mapsme context, in previous incarnations it was encoded separately from polygon, so the 'casing-width' and casing-color were just automatically promoted to render the border - the linear geometry. There wasn't area.border around, because it was supported via LineRuleProto().

If your refactoring led to area.border being used, just fill it from casing-* fields as in https://github.com/rokuz/kothic/blame/6c1f59ca6e188cb05e5177447e7ef747941eed0c/src/libkomwm.py#L332 (note the commented out `or st.get('fill-color'))` suggesting this branch was used in polygon rendering too :)

2017-02-13 15:38 UTC, rokuz commented
To know whether i reinvent something i have to know whether it has been invented in mapsme context :) Anyway the link may be useful, appreciate it.

2017-02-13 15:59 UTC, rokuz commented
@Komzpa How do you feel about this implementation?

2017-02-13 16:13 UTC, Komzpa commented
Now it's compatible with other implementations, thanks :)

Just in case, you can check mapcss styles in JOSM or galileo's mobile https://getyourmap.com/our_technology/#mapcss or any other compatible engine.

2017-02-13 18:20 UTC, rokuz commented
@Zverik take a look and merge pls

2017-02-14 08:16 UTC, Zverik requested changes

2017-02-14 08:16 UTC, Zverik commented on src/libkomwm.py
> +                            dr_element.area.border.width = st.get('casing-width')
Я выше и ниже вижу, что ширина умножается на `WIDTH_SCALE`. Можешь и тут?

2017-02-14 08:31 UTC, rokuz commented on src/libkomwm.py
> +                            dr_element.area.border.width = st.get('casing-width')
Могу, если надо :) В рендеринге мы все равно не учитываем заданную ширину :)

2017-02-14 08:35 UTC, rokuz commented on src/libkomwm.py
> +                            dr_element.area.border.width = st.get('casing-width')
@Zverik done PTAL

2017-02-14 08:56 UTC, merged